name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: Test Type
        type: choice
        required: true
        options:
          - test
          - suite
      test_suite_name:
        description: Test / Suite Name
        required: true
      run_time:
        description: Run time for performance test
        required: false
      users:
        description: Number of users for performance test
        required: false
        type: number
        default: 1
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository source code
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build -t kb-ist-automation-test \
        --build-arg=RUN_TIME=${{ inputs.run_time }} \
        --build-arg=TEST_TYPE=${{ inputs.test_type }} \
        --build-arg=TEST_SUITE_NAME=${{ inputs.test_suite_name }} \
        --build-arg=NUM_USERS=${{ inputs.users }} .
    - name: Run Docker Container
      run: |
          docker run --name kb-ist-automation-test -i -v $(pwd):/app

    - name: Docker Container Logs
      run: |
          docker logs $(docker ps -aqf "name="kb-ist-automation-test")
