name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: Test Type
        type: choice
        required: true
        options:
          - recursive 
          - test
          - suite

      test_suite_name:
        description: Test / Suite Name
        required: true
        default: y
      
      run_time:
        description: Run time for performance test
        required: false
        default: y
      users:
        description: Number of users for performance test
        required: false
        type: string 
        default: text
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository source code
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        EXTRA_PARAMS=""
        if [ ${{ inputs.run_time }} != "" ]; then EXTRA_PARAMS+=" --reports=${{ inputs.run_time }}"; else EXTRA_PARAMS+=" --reports=n"; fi
        docker build -t kb-ist-automation-test \
        --build-arg=RUN_TIME="$EXTRA_PARAMS" \
        --build-arg=TEST_TYPE=${{ inputs.test_type }} \
        --build-arg=TEST_SUITE_NAME=${{ inputs.test_suite_name }} \
        --build-arg=NUM_USERS=${{ inputs.users }} .
    - name: Run Docker Container
      run: |
          docker run -i -v $(pwd):/app --name kb-ist-automation-test-container kb-ist-automation-test:latest 

    - name: Docker Container Logs
      run: |
          docker logs $(docker ps -aqf "name="kb-ist-automation-test-container")
