name: Pylint

on: 
  workflow_dispatch:
  pull_request:
   types:
    - opened
  pull_request_review:
   types:
      - submitted
  

jobs:
  build:
    if: ${{ github.event.pull_request.action == 'opened' || github.event.review.state == 'approved' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint . --reports=y --recursive=y --output-format=text --fail-under 2
