name: Pylint

on: 
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      id: pylint
      run: |
        STDOUT=$(pylint . --reports=y --recursive=y --output-format=text --exit-zero)
        echo "::set-output name=pylint-output::Thank you:😀"
    - uses: actions/github-script@v6
      if: ${{ always() }}
      with:
        script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '${{ steps.pylint.outputs.pylint-output }}'
            })
            
